---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::851725303642:role/test-oidc
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend-depi-pod
  labels:
    app: frontend-depi
spec:
  serviceAccountName: aws-test
  containers:
  - name: frontend-depi-container
    image: sragzhran/frontend_depi_project:latest 
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "0.5"
        memory: "256Mi"



