apiVersion: v1
kind: Service
metadata:
  name: frontend-depi-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: frontend-depi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
